name: Deploy to AWS
#helloworld
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1  # Frankfurt

      - name: Create abc.sh
        run: echo "${{ secrets.RUNAPP_SH }}" > abc.sh && chmod +x abc.sh

      - name: Debug abc.sh content
        run: cat abc.sh  # Debugging step to ensure abc.sh is correctly created

      - name: Launch EC2 instance
        run: |
          aws ec2 run-instances \
            --image-id ami-0c8db01b2e8e5298d \
            --instance-type t2.micro \
            --key-name mykey \
            --security-groups launch-wizard-2 \
            --count 1 \
            --user-data file://abc.sh
