name: Deploy to AWS
#helloworld
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1  # Frankfurt

      - name: Create and debug abc.sh
        run: |
          # Check if the RUNAPP_SH secret is correct
          echo "${{ secrets.RUNAPP_SH }}" > abc.sh
          cat abc.sh  # Output abc.sh content to debug
          chmod +x abc.sh
          echo "abc.sh created and ready"
          ls -l abc.sh  # Check the file permissions

      - name: Launch EC2 instance
        run: |
          aws ec2 run-instances \
            --image-id ami-07eef52105e8a2059 \
            --instance-type t2.micro \
            --key-name mykey \
            --security-groups launch-wizard-2 \
            --count 1 \
            --user-data "$(echo '${{ secrets.RUNAPP_SH }}')"
