name: Build and Push Docker Image to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repozytorium
      - name: Checkout repository
        uses: actions/checkout@v3

      # Logowanie do DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Budowanie obrazu
      - name: Build Docker image
        run: |
          docker build -t h3770k1k1/myapp:latest .

      # Pushowanie obrazu na DockerHub
      - name: Push Docker image
        run: |
          docker push h3770k1k1/myapp:latest
